apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: medi-connect
type: Opaque
stringData:
  auth-password: "1234"
  doctors-password: "1234"
  patients-password: "123456"
  appointment-password: "1234"
  payment-password: "babibuba"
  notification-password: "1234"
  telemedicine-password: "babibuba"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: medi-connect
type: Opaque
stringData:
  secret: "mediconnect-super-secret-key-mediconnect-super-secret-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: payhere-secrets
  namespace: medi-connect
type: Opaque
stringData:
  merchant-id: "1234717"
  merchant-secret: "MzgxNDE3NTQ0NzM1MjE0NzYyNjMyNjI4NzE3NjA5NDE1OTg5ODcwOQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: email-secrets
  namespace: medi-connect
type: Opaque
stringData:
  username: "ronelladias23@gmail.com"
  password: "irfv hika gcso keyh"
---
apiVersion: v1
kind: Secret
metadata:
  name: twilio-secrets
  namespace: medi-connect
type: Opaque
stringData:
  account-sid: "AC2a2a2075721c845f0a5c0d4fbda0ee3c"
  auth-token: "48f05da5154c7a7ff3d8d6afbc7b1213"
  phone-number: "+17126003085"
