apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: ronella/appointment-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          env:
            - name: SERVER_PORT
              value: "8088"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.minikube.internal:5432/appointments_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:8086"
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - port: 8088
      targetPort: 8088
