apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ronella/frontend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4200
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "4200"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 4200
      targetPort: 4200
