apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
        - name: payments-service
          image: ronella/payments-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.minikube.internal:5435/payment_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "babibuba"
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:8088"
            - name: TELEMEDICINE_SERVICE_URL
              value: "http://telemedicine-service:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments-service
  ports:
    - port: 8085
      targetPort: 8085
