apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: ronella/telemedicine-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: "host.minikube.internal"
            - name: DB_PORT
              value: "5436"
            - name: DB_NAME
              value: "telemedicine"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
spec:
  selector:
    app: telemedicine-service
  ports:
    - port: 3000
      targetPort: 3000
